import { CommonModule } from '@angular/common';
import { Component, signal } from '@angular/core';
import { ACCESS_FLOW_DIAGRAM, LOGIN_FLOW_DIAGRAM, SPA_PKCE_FLOW_DIAGRAM } from '../home/swimlane.data';
import { SwimlaneDiagramComponent } from '../../shared/swimlane-diagram.component';

@Component({
  standalone: true,
  imports: [CommonModule, SwimlaneDiagramComponent],
  template: `
    <article class="box">
      <h2 class="title is-5 mb-4">OIDC Flows</h2>
      <div class="tabs is-boxed mb-4">
        <ul>
          <li [class.is-active]="activeTab() === 'summary'">
            <a (click)="activeTab.set('summary')">Summary</a>
          </li>
          <li [class.is-active]="activeTab() === 'login-flow'">
            <a (click)="activeTab.set('login-flow')">Login flow (BFF)</a>
          </li>
          <li [class.is-active]="activeTab() === 'access-flow'">
            <a (click)="activeTab.set('access-flow')">Access flow (BFF)</a>
          </li>
          <li [class.is-active]="activeTab() === 'spa-pkce-flow'">
            <a (click)="activeTab.set('spa-pkce-flow')">SPA + PKCE (Public)</a>
          </li>
        </ul>
      </div>

      <div class="content" *ngIf="activeTab() === 'summary'">
        <p>This app uses <strong>BFF (Backend-For-Frontend)</strong> architecture where the Node backend handles all OIDC interactions.</p>
        
        <div class="columns mt-4">
          <div class="column">
            <h4 class="title is-6">BFF Architecture (This App)</h4>
            <ul>
              <li><strong>Refresh tokens</strong> never exposed to browser</li>
              <li>Backend can enforce additional security policies</li>
              <li>Simpler Angular code (no token management)</li>
              <li>Session stored server-side (httpOnly cookies)</li>
              <li>Better for confidential clients with secrets</li>
            </ul>
          </div>
          <div class="column">
            <h4 class="title is-6">SPA + PKCE (Reference Only)</h4>
            <ul>
              <li>Tokens stored in browser memory</li>
              <li>PKCE protects code exchange without client secret</li>
              <li>SPA handles all OIDC logic directly</li>
              <li>Good for public clients (mobile, SPA)</li>
              <li><strong>Not implemented in this tutorial</strong></li>
            </ul>
          </div>
        </div>

        <p><strong>Note:</strong> The "SPA + PKCE" tab shows a conceptual flow for educational purposes. This application implements BFF architecture only.</p>
      </div>

      <div class="content" *ngIf="activeTab() === 'login-flow'">
        <p><strong>Summary:</strong> Angular does not handle OIDC tokens directly. The Node backend owns login/callback/session.</p>
        <div class="mt-4">
          <app-swimlane-diagram [diagram]="loginFlowDiagram"></app-swimlane-diagram>
        </div>
        <div class="mt-4">
          <p><strong>Notes:</strong></p>
          <ul>
            <li>Real tokens are stored only in backend session state.</li>
            <li>Angular checks auth state via <code>/api/auth/status</code> and consumes protected APIs.</li>
            <li>Angular never calls Keycloak directly in this flow.</li>
          </ul>
        </div>
      </div>

      <div class="content" *ngIf="activeTab() === 'access-flow'">
        <p><strong>Summary:</strong> For protected routes, Angular validates session state and backend validates/refreshes token before calling Keycloak.</p>
        <div class="mt-4">
          <app-swimlane-diagram [diagram]="accessFlowDiagram"></app-swimlane-diagram>
        </div>
        <div class="mt-4">
          <p><strong>Notes:</strong></p>
          <ul>
            <li>If no session exists, Angular blocks the protected route and redirects to Home.</li>
            <li>When calling <code>/api/oidc/*</code>, backend applies <code>authGuard</code> and refresh middleware when needed.</li>
            <li>If refresh succeeds, backend updates the session and continues the Keycloak call.</li>
          </ul>
        </div>
      </div>

      <div class="content" *ngIf="activeTab() === 'spa-pkce-flow'">
        <p><strong>Summary:</strong> In a public client (SPA/mobile), there is no backend secret. PKCE protects authorization code exchange.</p>
        <div class="mt-4">
          <app-swimlane-diagram [diagram]="spaPkceFlowDiagram"></app-swimlane-diagram>
        </div>
        <div class="mt-4">
          <p><strong>Notes:</strong></p>
          <ul>
            <li><code>code_verifier</code> is generated by the SPA and never sent in the authorize request.</li>
            <li><code>code_challenge</code> is sent to Keycloak; later the verifier must match during token exchange.</li>
            <li>PKCE prevents authorization code interception attacks for public clients.</li>
          </ul>
        </div>
      </div>
    </article>
  `
})
export class FlowsPageComponent {
  readonly activeTab = signal<'summary' | 'login-flow' | 'access-flow' | 'spa-pkce-flow'>('summary');
  readonly loginFlowDiagram = LOGIN_FLOW_DIAGRAM;
  readonly accessFlowDiagram = ACCESS_FLOW_DIAGRAM;
  readonly spaPkceFlowDiagram = SPA_PKCE_FLOW_DIAGRAM;
}
